// ABOUT: File storing dummy data for development purposes

import { Customer } from './customer-data';
import { Department } from './department-data';
import { InvoiceStatus, InvoiceType } from './quote/invoice.model';
import { ProductType } from './quote/items-services.model';
import { QuoteStatus } from './quote/quote.model';
import { TransactionType } from './transaction/transaction.model';
import { TransactionStatus } from './transaction/transaction.model';

// QUOTES
export const DUMMY_QUOTES = [
  {
    quoteNumber: '1000',
    department: Department.WEBSITE,
    dateCreated: '25-07-2024',
    dateOfExpiry: '25-08-2024',
    customer: Customer.FT_GULLY.name,
    customerID: Customer.FT_GULLY.customerID,
    description: 'Website design',
    preparedFor: 'Ben',
    customerPhone: '0456789012',
    customerEmail: 'ben@ft-gully.net.au',
    preparedBy: 'John',
    status: QuoteStatus.Sent,
    specialConditions: '',
    notes: '',
  },
  {
    quoteNumber: '1001',
    department: Department.ECLIPSE_DESKTOP,
    dateCreated: '22-07-2024',
    dateOfExpiry: '22-08-2024',
    customer: Customer.JAYCO_SYDNEY.name,
    customerID: Customer.JAYCO_SYDNEY.customerID,
    description: 'Domain registration',
    preparedFor: 'Harry',
    customerPhone: '0456789123',
    customerEmail: 'harry@jayco-sydney.com.au',
    preparedBy: 'Jill',
    status: QuoteStatus.Draft,
    specialConditions: '',
    notes: '',
  },
  {
    quoteNumber: '1002',
    department: Department.CRM,
    dateCreated: '20-07-2024',
    dateOfExpiry: '20-08-2024',
    customer: Customer.NORTHERN_MOTORS.name,
    customerID: Customer.NORTHERN_MOTORS.customerID,
    description: 'CRM system implementation',
    preparedFor: 'Anna',
    customerPhone: '0467891234',
    customerEmail: 'anna@northern-motors.com.au',
    preparedBy: 'Michelle',
    status: QuoteStatus.Signed,
    specialConditions: '',
    notes: '',
  },
  {
    quoteNumber: '1003',
    department: Department.ERP,
    dateCreated: '18-07-2024',
    dateOfExpiry: '18-08-2024',
    customer: Customer.SMITH_AUTO.name,
    customerID: Customer.SMITH_AUTO.customerID,
    description: 'ERP software integration',
    preparedFor: 'Joseph',
    customerPhone: '0478912345',
    customerEmail: 'joseph@smith-auto.com.au',
    preparedBy: 'Tom',
    status: QuoteStatus.Draft,
    specialConditions: '',
    notes: '',
  },
  {
    quoteNumber: '1004',
    department: Department.MOBILE_APP,
    dateCreated: '15-07-2024',
    dateOfExpiry: '15-08-2024',
    customer: Customer.AUTOWORLD.name,
    customerID: Customer.AUTOWORLD.customerID,
    description: 'Mobile app development',
    preparedFor: 'Andy',
    customerPhone: '0489123456',
    customerEmail: 'andy@autoworld.com.au',
    preparedBy: 'Jane',
    status: QuoteStatus.Expired,
    specialConditions: '',
    notes: '',
  },
  {
    quoteNumber: '1005',
    department: Department.WEBSITE,
    dateCreated: '10-07-2024',
    dateOfExpiry: '10-08-2024',
    customer: Customer.GREEN_VALLEY_CARS.name,
    customerID: Customer.GREEN_VALLEY_CARS.customerID,
    description: 'Data analytics service',
    preparedFor: 'Mick',
    customerPhone: '0491234567',
    customerEmail: 'mick@green-valley-cars.com.au',
    preparedBy: 'Mike',
    status: QuoteStatus.Cancelled,
    specialConditions: '',
    notes: '',
  },
  {
    quoteNumber: '1006',
    department: Department.CLOUD_SERVICES,
    dateCreated: '08-07-2024',
    dateOfExpiry: '08-08-2024',
    customer: Customer.QUICKFIX_AUTO.name,
    customerID: Customer.QUICKFIX_AUTO.customerID,
    description: 'Cloud infrastructure setup',
    preparedFor: 'Jason',
    customerPhone: '0412345678',
    customerEmail: 'jason@quickfix-auto.com.au',
    preparedBy: 'Lucy',
    status: QuoteStatus.Draft,
    specialConditions: '',
    notes: '',
  },
  {
    quoteNumber: '1007',
    department: Department.SECURITY,
    dateCreated: '05-07-2024',
    dateOfExpiry: '05-08-2024',
    customer: Customer.SAFERIDE_DEALERSHIPS.name,
    customerID: Customer.SAFERIDE_DEALERSHIPS.customerID,
    description: 'Cybersecurity implementation',
    preparedFor: 'Manuel',
    customerPhone: '0423456789',
    customerEmail: 'manuel@saferide-dealerships.com.au',
    preparedBy: 'Eve',
    status: QuoteStatus.Signed,
    specialConditions: '',
    notes: '',
  },
  {
    quoteNumber: '1008',
    department: Department.SOFTWARE_UPDATE,
    dateCreated: '02-07-2024',
    dateOfExpiry: '02-08-2024',
    customer: Customer.SPEEDY_CARS.name,
    customerID: Customer.SPEEDY_CARS.customerID,
    description: 'Software version upgrade',
    preparedFor: 'Chris',
    customerPhone: '0434567890',
    customerEmail: 'chris@speedy-cars.com.au',
    preparedBy: 'Leo',
    status: QuoteStatus.Sent,
    specialConditions: '',
    notes: '',
  },
  {
    quoteNumber: '1009',
    department: Department.TRAINING,
    dateCreated: '28-06-2024',
    dateOfExpiry: '28-07-2024',
    customer: Customer.AUTO_EXPERTS.name,
    customerID: Customer.AUTO_EXPERTS.customerID,
    description: 'Staff training on new software',
    preparedFor: 'Anthony',
    customerPhone: '0445678901',
    customerEmail: 'anthony@auto-experts.com.au',
    preparedBy: 'Nina',
    status: QuoteStatus.Expired,
    specialConditions: '',
    notes: '',
  },
  {
    quoteNumber: '1010',
    department: Department.CONSULTATION,
    dateCreated: '25-06-2024',
    dateOfExpiry: '25-07-2024',
    customer: Customer.PREMIER_MOTORS.name,
    customerID: Customer.PREMIER_MOTORS.customerID,
    description: 'IT infrastructure consultation',
    preparedFor: 'Warren',
    customerPhone: '0456789012',
    customerEmail: 'warren@premier-motors.com.au',
    preparedBy: 'Oscar',
    status: QuoteStatus.Signed,
    specialConditions: '',
    notes: '',
  },
  {
    quoteNumber: '1011',
    department: Department.SUPPORT,
    dateCreated: '20-06-2024',
    dateOfExpiry: '20-07-2024',
    customer: Customer.QUALITY_CARS.name,
    customerID: Customer.QUALITY_CARS.customerID,
    description: 'Annual support and maintenance',
    preparedFor: 'David',
    customerPhone: '0467890123',
    customerEmail: 'david@quality-cars.com.au',
    preparedBy: 'Paul',
    status: QuoteStatus.Draft,
    specialConditions: '',
    notes: '',
  },

  {
    quoteNumber: '1012',
    department: Department.MOBILE_APP,
    dateCreated: '15-06-2024',
    dateOfExpiry: '15-07-2024',
    customer: Customer.AUTO_EXPERTS.name,
    customerID: Customer.AUTO_EXPERTS.customerID,
    description: 'Mobile app for vehicle tracking',
    preparedFor: 'Lucas',
    customerPhone: '0487654321',
    customerEmail: 'lucas@alpha-automotive.com.au',
    preparedBy: 'Sarah',
    status: QuoteStatus.Draft,
    specialConditions: '',
    notes: '',
  },
  {
    quoteNumber: '1013',
    department: Department.CRM,
    dateCreated: '10-06-2024',
    dateOfExpiry: '10-07-2024',
    customer: Customer.SAFERIDE_DEALERSHIPS.name,
    customerID: Customer.SAFERIDE_DEALERSHIPS.customerID,
    description: 'CRM for logistics management',
    preparedFor: 'Mark',
    customerPhone: '0423456789',
    customerEmail: 'mark@beta-transport.com.au',
    preparedBy: 'Emily',
    status: QuoteStatus.Sent,
    specialConditions: '',
    notes: '',
  },
  {
    quoteNumber: '1014',
    department: Department.WEBSITE,
    dateCreated: '05-06-2024',
    dateOfExpiry: '05-07-2024',
    customer: Customer.SMITH_AUTO.name,
    customerID: Customer.SMITH_AUTO.customerID,
    description: 'Website redesign and hosting',
    preparedFor: 'Sophia',
    customerPhone: '0412345678',
    customerEmail: 'sophia@gamma-motors.com.au',
    preparedBy: 'Jack',
    status: QuoteStatus.Expired,
    specialConditions: '',
    notes: '',
  },
  {
    quoteNumber: '1015',
    department: Department.ECLIPSE_DESKTOP,
    dateCreated: '01-06-2024',
    dateOfExpiry: '01-07-2024',
    customer: Customer.FT_GULLY.name,
    customerID: Customer.FT_GULLY.customerID,
    description: 'Desktop app for inventory management',
    preparedFor: 'James',
    customerPhone: '0498765432',
    customerEmail: 'james@delta-autos.com.au',
    preparedBy: 'Ella',
    status: QuoteStatus.Signed,
    specialConditions: '',
    notes: '',
  },
  {
    quoteNumber: '1016',
    department: Department.CLOUD_SERVICES,
    dateCreated: '25-05-2024',
    dateOfExpiry: '25-06-2024',
    customer: Customer.GREEN_VALLEY_CARS.name,
    customerID: Customer.GREEN_VALLEY_CARS.customerID,
    description: 'Cloud storage solutions',
    preparedFor: 'Zara',
    customerPhone: '0435678901',
    customerEmail: 'zara@omega-motors.com.au',
    preparedBy: 'Sam',
    status: QuoteStatus.Draft,
    specialConditions: '',
    notes: '',
  },
];

// INVOICES
export const DUMMY_INVOICES = [
  {
    quoteNumber: '1000',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1000-1',
    dateSent: '2024-07-25',
    dateDue: '2024-08-25',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1000',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1000-2',
    dateSent: '2024-07-26',
    dateDue: '2024-08-26',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1000',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1000-3',
    dateSent: '2024-07-27',
    dateDue: '2024-08-27',
    status: InvoiceStatus.Sent,
  },

  // Invoices for quoteNumber '1001'
  {
    quoteNumber: '1001',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1001-1',
    dateSent: '2024-07-22',
    dateDue: '2024-08-22',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1001',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1001-2',
    dateSent: '2024-07-23',
    dateDue: '2024-08-23',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1001',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1001-3',
    dateSent: '2024-07-24',
    dateDue: '2024-08-24',
    status: InvoiceStatus.NotSent,
  },

  // Invoices for quoteNumber '1002'
  {
    quoteNumber: '1002',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1002-1',
    dateSent: '2024-07-20',
    dateDue: '2024-08-20',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1002',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1002-2',
    dateSent: '2024-07-21',
    dateDue: '2024-08-21',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1002',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1002-3',
    dateSent: '2024-07-22',
    dateDue: '2024-08-22',
    status: InvoiceStatus.Sent,
  },

  // Invoices for quoteNumber '1003'
  {
    quoteNumber: '1003',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1003-1',
    dateSent: '2024-07-18',
    dateDue: '2024-08-18',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1003',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1003-2',
    dateSent: '2024-07-19',
    dateDue: '2024-08-19',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1003',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1003-3',
    dateSent: '2024-07-20',
    dateDue: '2024-08-20',
    status: InvoiceStatus.Sent,
  },

  // Invoices for quoteNumber '1004'
  {
    quoteNumber: '1004',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1004-1',
    dateSent: '2024-07-15',
    dateDue: '2024-08-15',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1004',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1004-2',
    dateSent: '2024-07-16',
    dateDue: '2024-08-16',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1004',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1004-3',
    dateSent: '2024-07-17',
    dateDue: '2024-08-17',
    status: InvoiceStatus.NotSent,
  },

  // Invoices for quoteNumber '1005'
  {
    quoteNumber: '1005',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1005-1',
    dateSent: '2024-07-10',
    dateDue: '2024-08-10',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1005',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1005-2',
    dateSent: '2024-07-11',
    dateDue: '2024-08-11',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1005',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1005-3',
    dateSent: '2024-07-12',
    dateDue: '2024-08-12',
    status: InvoiceStatus.Sent,
  },

  // Invoices for quoteNumber '1006'
  {
    quoteNumber: '1006',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1006-1',
    dateSent: '2024-07-08',
    dateDue: '2024-08-08',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1006',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1006-2',
    dateSent: '2024-07-09',
    dateDue: '2024-08-09',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1006',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1006-3',
    dateSent: '2024-07-10',
    dateDue: '2024-08-10',
    status: InvoiceStatus.NotSent,
  },

  // Invoices for quoteNumber '1007'
  {
    quoteNumber: '1007',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1007-1',
    dateSent: '2024-07-05',
    dateDue: '2024-08-05',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1007',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1007-2',
    dateSent: '2024-07-06',
    dateDue: '2024-08-06',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1007',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1007-3',
    dateSent: '2024-07-07',
    dateDue: '2024-08-07',
    status: InvoiceStatus.Sent,
  },

  // Invoices for quoteNumber '1008'
  {
    quoteNumber: '1008',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1008-1',
    dateSent: '2024-07-02',
    dateDue: '2024-08-02',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1008',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1008-2',
    dateSent: '2024-07-03',
    dateDue: '2024-08-03',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1008',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1008-3',
    dateSent: '2024-07-04',
    dateDue: '2024-08-04',
    status: InvoiceStatus.NotSent,
  },

  // Invoices for quoteNumber '1009'
  {
    quoteNumber: '1009',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1009-1',
    dateSent: '2024-06-28',
    dateDue: '2024-07-28',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1009',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1009-2',
    dateSent: '2024-06-29',
    dateDue: '2024-07-29',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1009',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1009-3',
    dateSent: '2024-06-30',
    dateDue: '2024-07-30',
    status: InvoiceStatus.Sent,
  },

  // Invoices for quoteNumber '1010'
  {
    quoteNumber: '1010',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1010-1',
    dateSent: '2024-06-25',
    dateDue: '2024-07-25',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1010',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1010-2',
    dateSent: '2024-06-26',
    dateDue: '2024-07-26',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1010',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1010-3',
    dateSent: '2024-06-27',
    dateDue: '2024-07-27',
    status: InvoiceStatus.Sent,
  },

  // Invoices for quoteNumber '1011'
  {
    quoteNumber: '1011',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1011-1',
    dateSent: '2024-06-20',
    dateDue: '2024-07-20',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1011',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1011-2',
    dateSent: '2024-06-21',
    dateDue: '2024-07-21',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1011',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1011-3',
    dateSent: '2024-06-22',
    dateDue: '2024-07-22',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1012',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1012-1',
    dateSent: '2024-06-15',
    dateDue: '2024-07-15',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1012',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1012-2',
    dateSent: '2024-06-16',
    dateDue: '2024-07-16',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1012',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1012-3',
    dateSent: '2024-06-17',
    dateDue: '2024-07-17',
    status: InvoiceStatus.NotSent,
  },

  // Invoices for quoteNumber '1013'
  {
    quoteNumber: '1013',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1013-1',
    dateSent: '2024-06-10',
    dateDue: '2024-07-10',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1013',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1013-2',
    dateSent: '2024-06-11',
    dateDue: '2024-07-11',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1013',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1013-3',
    dateSent: '2024-06-12',
    dateDue: '2024-07-12',
    status: InvoiceStatus.Sent,
  },

  // Invoices for quoteNumber '1014'
  {
    quoteNumber: '1014',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1014-1',
    dateSent: '2024-06-05',
    dateDue: '2024-07-05',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1014',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1014-2',
    dateSent: '2024-06-06',
    dateDue: '2024-07-06',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1014',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1014-3',
    dateSent: '2024-06-07',
    dateDue: '2024-07-07',
    status: InvoiceStatus.NotSent,
  },

  // Invoices for quoteNumber '1015'
  {
    quoteNumber: '1015',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1015-1',
    dateSent: '2024-06-01',
    dateDue: '2024-07-01',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1015',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1015-2',
    dateSent: '2024-06-02',
    dateDue: '2024-07-02',
    status: InvoiceStatus.Sent,
  },
  {
    quoteNumber: '1015',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1015-3',
    dateSent: '2024-06-03',
    dateDue: '2024-07-03',
    status: InvoiceStatus.Sent,
  },

  // Invoices for quoteNumber '1016'
  {
    quoteNumber: '1016',
    invoiceType: InvoiceType.HoldingDeposit,
    invoiceNumber: 'INV-1016-1',
    dateSent: '2024-05-25',
    dateDue: '2024-06-25',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1016',
    invoiceType: InvoiceType.InstallTravelCost,
    invoiceNumber: 'INV-1016-2',
    dateSent: '2024-05-26',
    dateDue: '2024-06-26',
    status: InvoiceStatus.NotSent,
  },
  {
    quoteNumber: '1016',
    invoiceType: InvoiceType.FinalInvoice,
    invoiceNumber: 'INV-1016-3',
    dateSent: '2024-05-27',
    dateDue: '2024-06-27',
    status: InvoiceStatus.NotSent,
  },
];

// ITEMS-SERVICES
export const DUMMY_ITEMS_SERVICES = [
  {
    quoteNumber: '1000',
    productType: ProductType.InstallTrainingTravel,
    productCode: 'ITTC001',
    description: '1-year web hosting plan',
    quantity: 1,
    unitPrice: 120.0,
    totalPriceInclGST: 132.0,
    totalPriceExclGST: 120.0,
  },
  {
    quoteNumber: '1001',
    productType: ProductType.Maintenance,
    productCode: 'MN002',
    description: 'Domain registration for 2 years',
    quantity: 1,
    unitPrice: 25.0,
    totalPriceInclGST: 27.5,
    totalPriceExclGST: 25.0,
  },
  {
    quoteNumber: '1002',
    productType: ProductType.AdditionalItems,
    productCode: 'AI003',
    description: 'CRM software license for 10 users',
    quantity: 10,
    unitPrice: 50.0,
    totalPriceInclGST: 550.0,
    totalPriceExclGST: 500.0,
  },
  {
    quoteNumber: '1003',
    productType: ProductType.InstallTrainingTravel,
    productCode: 'ITTC004',
    description: 'ERP finance module',
    quantity: 1,
    unitPrice: 800.0,
    totalPriceInclGST: 880.0,
    totalPriceExclGST: 800.0,
  },
  {
    quoteNumber: '1004',
    productType: ProductType.Maintenance,
    productCode: 'MN005',
    description: 'Mobile app UI/UX design',
    quantity: 1,
    unitPrice: 1500.0,
    totalPriceInclGST: 1650.0,
    totalPriceExclGST: 1500.0,
  },
  {
    quoteNumber: '1005',
    productType: ProductType.AdditionalItems,
    productCode: 'AI006',
    description: 'Data analysis service',
    quantity: 1,
    unitPrice: 2000.0,
    totalPriceInclGST: 2200.0,
    totalPriceExclGST: 2000.0,
  },
  {
    quoteNumber: '1006',
    productType: ProductType.InstallTrainingTravel,
    productCode: 'ITTC007',
    description: '500GB cloud storage',
    quantity: 1,
    unitPrice: 100.0,
    totalPriceInclGST: 110.0,
    totalPriceExclGST: 100.0,
  },
  {
    quoteNumber: '1007',
    productType: ProductType.Maintenance,
    productCode: 'MN008',
    description: 'Comprehensive security audit',
    quantity: 1,
    unitPrice: 1200.0,
    totalPriceInclGST: 1320.0,
    totalPriceExclGST: 1200.0,
  },
  {
    quoteNumber: '1008',
    productType: ProductType.AdditionalItems,
    productCode: 'AI009',
    description: 'Annual software update',
    quantity: 1,
    unitPrice: 300.0,
    totalPriceInclGST: 330.0,
    totalPriceExclGST: 300.0,
  },
  {
    quoteNumber: '1009',
    productType: ProductType.InstallTrainingTravel,
    productCode: 'ITTC010',
    description: 'Staff training session',
    quantity: 1,
    unitPrice: 500.0,
    totalPriceInclGST: 550.0,
    totalPriceExclGST: 500.0,
  },
  {
    quoteNumber: '1010',
    productType: ProductType.Maintenance,
    productCode: 'MN011',
    description: 'IT infrastructure consultation',
    quantity: 1,
    unitPrice: 700.0,
    totalPriceInclGST: 770.0,
    totalPriceExclGST: 700.0,
  },
  {
    quoteNumber: '1011',
    productType: ProductType.AdditionalItems,
    productCode: 'AI012',
    description: 'Annual support and maintenance',
    quantity: 1,
    unitPrice: 1000.0,
    totalPriceInclGST: 1100.0,
    totalPriceExclGST: 1000.0,
  },
  {
    quoteNumber: '1000',
    productType: ProductType.InstallTrainingTravel,
    productCode: 'ITTC013',
    description: 'Monthly SEO service',
    quantity: 12,
    unitPrice: 100.0,
    totalPriceInclGST: 1320.0,
    totalPriceExclGST: 1200.0,
  },
  {
    quoteNumber: '1001',
    productType: ProductType.Maintenance,
    productCode: 'MN014',
    description: 'Email hosting for 1 year',
    quantity: 1,
    unitPrice: 50.0,
    totalPriceInclGST: 55.0,
    totalPriceExclGST: 50.0,
  },
  {
    quoteNumber: '1002',
    productType: ProductType.AdditionalItems,
    productCode: 'AI015',
    description: 'CRM training session',
    quantity: 1,
    unitPrice: 600.0,
    totalPriceInclGST: 660.0,
    totalPriceExclGST: 600.0,
  },
  {
    quoteNumber: '1003',
    productType: ProductType.InstallTrainingTravel,
    productCode: 'ITTC016',
    description: 'Customization of ERP modules',
    quantity: 1,
    unitPrice: 2000.0,
    totalPriceInclGST: 2200.0,
    totalPriceExclGST: 2000.0,
  },
  {
    quoteNumber: '1004',
    productType: ProductType.Maintenance,
    productCode: 'MN017',
    description: 'Full mobile app development',
    quantity: 1,
    unitPrice: 3000.0,
    totalPriceInclGST: 3300.0,
    totalPriceExclGST: 3000.0,
  },
  {
    quoteNumber: '1005',
    productType: ProductType.AdditionalItems,
    productCode: 'AI018',
    description: 'Data migration service',
    quantity: 1,
    unitPrice: 1500.0,
    totalPriceInclGST: 1650.0,
    totalPriceExclGST: 1500.0,
  },
  {
    quoteNumber: '1006',
    productType: ProductType.InstallTrainingTravel,
    productCode: 'ITTC019',
    description: 'Initial cloud setup service',
    quantity: 1,
    unitPrice: 500.0,
    totalPriceInclGST: 550.0,
    totalPriceExclGST: 500.0,
  },
  {
    quoteNumber: '1007',
    productType: ProductType.Maintenance,
    productCode: 'MN020',
    description: 'Cybersecurity training',
    quantity: 1,
    unitPrice: 1000.0,
    totalPriceInclGST: 1100.0,
    totalPriceExclGST: 1000.0,
  },
];

export const DUMMY_TRANSACTIONS = [
  {
    transactionNumber: '2000',
    bulkTransactionNumber: '3001',
    transactionType: TransactionType.GoogleAds,
    customer: 'ACME Corp',
    productCode: 'GA-001',
    description: 'Google Ads campaign',
    quantity: '100',
    unitPriceInclGST: '55.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '01-08-2024',
    status: TransactionStatus.Draft,
  },
  {
    transactionNumber: '2001',
    bulkTransactionNumber: '3001',
    transactionType: TransactionType.FacebookAds,
    customer: 'Beta Ltd',
    productCode: 'FB-001',
    description: 'Facebook Ads campaign',
    quantity: '50',
    unitPriceInclGST: '22.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '02-08-2024',
    status: TransactionStatus.RequestedInvoice,
  },
  {
    transactionNumber: '2002',
    bulkTransactionNumber: '3001',
    transactionType: TransactionType.DMSSupport,
    customer: 'Gamma Inc',
    productCode: 'DMS-001',
    description: 'DMS support service',
    quantity: '10',
    unitPriceInclGST: '110.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '03-08-2024',
    status: TransactionStatus.Sent,
  },
  {
    transactionNumber: '2003',
    bulkTransactionNumber: '3002',
    transactionType: TransactionType.Installation,
    customer: 'Delta Co',
    productCode: 'INST-001',
    description: 'Software installation',
    quantity: '5',
    unitPriceInclGST: '220.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '04-08-2024',
    status: TransactionStatus.Paid,
  },
  {
    transactionNumber: '2004',
    bulkTransactionNumber: '3002',
    transactionType: TransactionType.Travel,
    customer: 'Epsilon LLC',
    productCode: 'TRV-001',
    description: 'Travel expenses',
    quantity: '3',
    unitPriceInclGST: '330.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '05-08-2024',
    status: TransactionStatus.Expired,
  },
  {
    transactionNumber: '2005',
    bulkTransactionNumber: '3002',
    transactionType: TransactionType.ITSupport,
    customer: 'Zeta Pvt',
    productCode: 'ITS-001',
    description: 'IT support service',
    quantity: '20',
    unitPriceInclGST: '55.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '06-08-2024',
    status: TransactionStatus.Cancelled,
  },
  {
    transactionNumber: '2006',
    bulkTransactionNumber: '3003',
    transactionType: TransactionType.Maintenance,
    customer: 'Eta Solutions',
    productCode: 'MNT-001',
    description: 'Maintenance service',
    quantity: '15',
    unitPriceInclGST: '77.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '07-08-2024',
    status: TransactionStatus.Draft,
  },
  {
    transactionNumber: '2007',
    bulkTransactionNumber: '3004',
    transactionType: TransactionType.GoogleAds,
    customer: 'Theta Systems',
    productCode: 'GA-002',
    description: 'Google Ads campaign',
    quantity: '25',
    unitPriceInclGST: '55.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '08-08-2024',
    status: TransactionStatus.RequestedInvoice,
  },
  {
    transactionNumber: '2008',
    bulkTransactionNumber: '3004',
    transactionType: TransactionType.FacebookAds,
    customer: 'Iota Enterprises',
    productCode: 'FB-002',
    description: 'Facebook Ads campaign',
    quantity: '40',
    unitPriceInclGST: '22.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '09-08-2024',
    status: TransactionStatus.Sent,
  },
  {
    transactionNumber: '2009',
    bulkTransactionNumber: '3005',
    transactionType: TransactionType.DMSSupport,
    customer: 'Kappa Industries',
    productCode: 'DMS-002',
    description: 'DMS support service',
    quantity: '8',
    unitPriceInclGST: '110.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '10-08-2024',
    status: TransactionStatus.Paid,
  },

  {
    transactionNumber: '2010',
    bulkTransactionNumber: '3006',
    transactionType: TransactionType.FacebookAds,
    customer: 'Beta Ltd',
    productCode: 'FB-001',
    description: 'Facebook Ads campaign',
    quantity: '50',
    unitPriceInclGST: '22.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '02-08-2024',
    status: TransactionStatus.RequestedInvoice,
  },
  {
    transactionNumber: '2011',
    bulkTransactionNumber: '3006',
    transactionType: TransactionType.DMSSupport,
    customer: 'Gamma Inc',
    productCode: 'DMS-001',
    description: 'DMS support service',
    quantity: '10',
    unitPriceInclGST: '110.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '03-08-2024',
    status: TransactionStatus.Sent,
  },
  {
    transactionNumber: '2012',
    bulkTransactionNumber: '3007',
    transactionType: TransactionType.Installation,
    customer: 'Delta Co',
    productCode: 'INST-001',
    description: 'Software installation',
    quantity: '5',
    unitPriceInclGST: '220.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '04-08-2024',
    status: TransactionStatus.Paid,
  },
  {
    transactionNumber: '2013',
    bulkTransactionNumber: '3007',
    transactionType: TransactionType.Travel,
    customer: 'Epsilon LLC',
    productCode: 'TRV-001',
    description: 'Travel expenses',
    quantity: '3',
    unitPriceInclGST: '330.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '05-08-2024',
    status: TransactionStatus.Expired,
  },
  {
    transactionNumber: '2014',
    bulkTransactionNumber: '3007',
    transactionType: TransactionType.ITSupport,
    customer: 'Zeta Pvt',
    productCode: 'ITS-001',
    description: 'IT support service',
    quantity: '20',
    unitPriceInclGST: '55.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '06-08-2024',
    status: TransactionStatus.Cancelled,
  },
  {
    transactionNumber: '2015',
    bulkTransactionNumber: '3008',
    transactionType: TransactionType.Maintenance,
    customer: 'Eta Solutions',
    productCode: 'MNT-001',
    description: 'Maintenance service',
    quantity: '15',
    unitPriceInclGST: '77.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '07-08-2024',
    status: TransactionStatus.Draft,
  },

  {
    transactionNumber: '2016',
    bulkTransactionNumber: '3009',
    transactionType: TransactionType.GoogleAds,
    customer: 'ACME Corp',
    productCode: 'GA-001',
    description: 'Google Ads campaign',
    quantity: '100',
    unitPriceInclGST: '55.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '01-08-2024',
    status: TransactionStatus.Draft,
  },
  {
    transactionNumber: '2017',
    bulkTransactionNumber: '3009',
    transactionType: TransactionType.FacebookAds,
    customer: 'Beta Ltd',
    productCode: 'FB-001',
    description: 'Facebook Ads campaign',
    quantity: '50',
    unitPriceInclGST: '22.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '02-08-2024',
    status: TransactionStatus.RequestedInvoice,
  },
  {
    transactionNumber: '2018',
    bulkTransactionNumber: '3010',
    transactionType: TransactionType.DMSSupport,
    customer: 'Gamma Inc',
    productCode: 'DMS-001',
    description: 'DMS support service',
    quantity: '10',
    unitPriceInclGST: '110.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '03-08-2024',
    status: TransactionStatus.Sent,
  },
  {
    transactionNumber: '2019',
    bulkTransactionNumber: '3011',
    transactionType: TransactionType.Installation,
    customer: 'Delta Co',
    productCode: 'INST-001',
    description: 'Software installation',
    quantity: '5',
    unitPriceInclGST: '220.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '04-08-2024',
    status: TransactionStatus.Paid,
  },
  {
    transactionNumber: '2020',
    bulkTransactionNumber: '3012',
    transactionType: TransactionType.Travel,
    customer: 'Epsilon LLC',
    productCode: 'TRV-001',
    description: 'Travel expenses',
    quantity: '3',
    unitPriceInclGST: '330.00',
    unitPriceExclGST: '',
    totalPriceInclGST: '',
    totalPriceExcl: '',
    dateCreated: '05-08-2024',
    status: TransactionStatus.Expired,
  },
];

// BULK TRANSACTIONS
export const DUMMY_BULK_TRANSACTIONS = [
  {
    bulkTransactionNumber: '3001',
    dateCreated: '01-08-2024',
  },
  {
    bulkTransactionNumber: '3002',
    dateCreated: '04-08-2024',
  },
  {
    bulkTransactionNumber: '3003',
    dateCreated: '07-08-2024',
  },
  {
    bulkTransactionNumber: '3004',
    dateCreated: '08-08-2024',
  },
  {
    bulkTransactionNumber: '3005',
    dateCreated: '10-08-2024',
  },

  {
    bulkTransactionNumber: '3006',
    dateCreated: '12-08-2024',
  },
  {
    bulkTransactionNumber: '3007',
    dateCreated: '04-09-2024',
  },
  {
    bulkTransactionNumber: '3008',
    dateCreated: '10-09-2024',
  },
  {
    bulkTransactionNumber: '3009',
    dateCreated: '20-09-2024',
  },
  {
    bulkTransactionNumber: '3010',
    dateCreated: '22-09-2024',
  },

  {
    bulkTransactionNumber: '3011',
    dateCreated: '24-09-2024',
  },
  {
    bulkTransactionNumber: '3012',
    dateCreated: '01-10-2024',
  },
];
